# importing protobuf file
import bfcp
from random import randint
from uuid import uuid4

class Conn(object):

    def make_request(self, _end_node_requirement):
        # make request object and send it
        connection_params = bfcp.ConnectionRoutingParams()
        connection_params.UUID = str(uuid4())
        connection_params.remaining_hops = float(randint(10,20))

        end_node_requirement = _end_node_requirement





    def send_request(self):
        pass
    
    def send_response(self):
        pass

message ConnectionRequest {
   ConnectionRoutingParams connection_params = 1;

   // The requirements on the End Node. This could specify that an end node needs to be within a
   // particular country, ip subnet, etc.
   EndNodeRequirement end_node_requirement = 2;

   string target_server_address = 3;
   int32 target_server_port = 4;

   // Public key generated by the original sender to sign the messages on the created connection.
   // This key should be created only for this connection, and discarded afterwards.
   bytes sender_connection_signing_key = 5;
}
