version: '3'
services:
  http_proxy:
    build:
      dockerfile: Dockerfile-http_proxy
      context: .
  test_bfcp:
    build:
      dockerfile: Dockerfile-http_proxy
      context: .
    working_dir: "/app"
    command: ["pytest"]
